Photogram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from modules.gallery import urls as gallery_urls
from modules.profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('allauth.urls')),
    path('', include(gallery_urls, namespace = 'gallery')),
    path('', include(profiles_urls, namespace = 'profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Photogram/modules/gallery/urls.py
from django.urls import path
from .views import HomePageView, PhotoDetailView, NewPhoto

app_name = 'gallery'

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("album/<int:pk>/", PhotoDetailView.as_view(), name="album"),
    path("album/new", NewPhoto.as_view(), name="new")
]

Photogram/modules/profiles/urls.py
from django.urls import path
from .views import ProfileDetailView

app_name = 'profiles'

urlpatterns = [
    path("profile/<str:username>/", ProfileDetailView.as_view(), name="detail"),
]

Photogram/modules/gallery/models.py
from django.contrib.auth.models import User
from django.db import models

class Photo(models.Model):
    author = models.ForeignKey(
                                User,
                                on_delete = models.CASCADE,
                            )
    title = models.CharField(max_length=80, blank=False, null=False)
    image = models.ImageField(upload_to='media/images/',blank=False )
    description = models.TextField(max_length=255, blank=True, null=False)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title[0:80]

Photogram/modules/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(
                                User,
                                on_delete=models.CASCADE,
                                related_name='profile'
                            )
    image = models.ImageField(upload_to='media/avatars/', default='/media/avatars/default_profile.png')
    headline = models.CharField(max_length=60, blank=True, null=False)
    city = models.CharField(max_length=60, blank=True, null=False)
    country = models.CharField(max_length=20, blank=True, null=False)

    def __str__(self):
        return self.user.username[0:30]
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new profile when a User is created."""
    if created:
            Profile.objects.create(user=instance)

Photogram/modules/gallery/views.py
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Photo


class HomePageView(TemplateView):
    http_method_names = ["get"]
    template_name = "gallery/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["photos"] = Photo.objects.all().order_by("-id")[0:30]
        return context
    
class PhotoDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "gallery/album.html"
    model = Photo
    context_object_name = "photo"

class NewPhoto(LoginRequiredMixin, CreateView):
    template_name = "gallery/new.html"
    model = Photo
    success_url = "/"
    fields = ["title", "image", "description"]

    def form_valid(self, form):
        """If the form is valid, redirect to the supplied URL."""
        
        def dispatch(self, request, *args, **kwargs):
            self.request = request
            return super().dispatch(request, *args, **kwargs)
        
        
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()

        return super().form_valid(form)

Photogram/modules/profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView

class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profile/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

Photogram/client/templates/config/bootstrap/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Photogram</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll ms-3 gap-3" style="--bs-scroll-height: 100px;">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Explore</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Jobs</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
            </li>
        </ul> -->
        <div class="collapse navbar-collapse mx-3" id="navbarScroll">
            <div class="input-group rounded">
                <input type="search" id="form1" class="form-control rounded bg-dark-subtle" placeholder="Search" aria-label="Search" aria-describedby="search-addon" style="color:white;" />
            </div>
        </div>
        {% if request.user.is_authenticated %}
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll gap-3" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gallery:new' %}">Upload</a>
                <!-- </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Notifications</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Messages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Cart</a>
                </li> -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="Left-aligned, right-aligned lg">
                        <img src="{{ user.profile.image.url }}" class="rounded-circle" width="30" height="30" alt="{{ user.username }}" />
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li class="ps-3">
                            <a class="link-light text-decoration-none fw-bolder" href="{% url 'profiles:detail' user.username %}">{{ user.username }}</a>
                        <li><a class="dropdown-item" href="{% url 'profiles:detail' user.username %}">View Profile</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll gap-3" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="#">Cart</a>
                    </li> -->
                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#signup-modal">
                        <li class="nav-item"><a class="text-white text-decoration-none" >Sign Up</a></li>
                    </button>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#login-modal">
                        <li class="nav-item"><a class="text-white text-decoration-none" >Sign In</a></li>
                    </button>
                </li>
            </ul>
        {% endif %}
        <!-- href="{% url 'account_signup' %}" -->
        <!-- href="{% url 'account_login' %}" -->
    </div>
</nav>

<!-- Sign Up Modal -->
<div class="modal fade" id="signup-modal" tabindex="-1" aria-labelledby="signup-modal-title" aria-hidden="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-dark" data-bs-theme="dark">
            <div class="modal-header" style="border-bottom: 0 none;">
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h1 class="modal-title fs-5 mb-3 text-center" id="signup-modal-title">Photogram</h1>
                <div class="d-grid gap-2 col-6 mx-auto">
                    <a href="{% url 'account_signup' %}" class="btn fa fa-envelope text-white" type="button" style="background: #7F7F7F; color: white;"> Sign up with Email</a>
                    <a href="#" class="btn fa fa-google" type="button" style="background: #dd4b39; color: white;"> Sign up with Google</a>
                    <a href="#" class="btn fa fa-facebook" type="button" style="background: #3B5998; color: white;"> Sign up with Facebook</a>
                </div>
            </div>
            <div class="modal-footer" style="border-top: 0 none; background-color:#16161a;">
                <div class="d-grid mx-auto">
                    <p class="m-0" style="color:white">Already have an account? <a href="{% url 'account_login' %}" style="text-decoration: none;">Sign In here</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Sign In Modal -->
<div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="login-modal-title" aria-hidden="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-dark" data-bs-theme="dark">
            <div class="modal-header" style="border-bottom: 0 none;">
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="text-light" method="POST" action="{% url 'account_login' %}">
                    {% csrf_token %}
                    {% if redirect_field_value %}
                        <input class="form-control shadow-none bg-dark-subtle" type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                    {% endif %}
                    <div class="mb-3 row justify-content-center">
                        <div class="col-sm-10">
                            <h1 class="modal-title fs-5" id="login-modal-title">Sign In</h1>
                        </div>
                    </div>
                    <p class="text-danger">
                        {{ form.non_field_errors.as_text }}
                    </p>
                    <div class="mb-3 row justify-content-center">
                        <div class="col-sm-10">
                            <label for="email" class="col-form-label">Email Address</label>
                            <input type="email" class="form-control shadow-none bg-dark-subtle" id="email_modal" aria-describedby="emailHelp" placeholder="Email Address" name="login">
                            <p id="email_Modal" class="text-danger">
                                {{ form.login.errors.as_text }}
                            </p>

                            <label for="inputPassword" class="col-form-label" >Password</label>
                            <input type="password" class="form-control shadow-none bg-dark-subtle" id="password_modal" aria-describedby="passwordHelp" placeholder="Password" name="password">
                            <p id="password_Modal" class="text-danger">
                                {{ form.password.errors.as_text }}
                            </p>

                            <div class="form-check mb-2">
                                <input class="form-check-input bg-dark-subtle" type="checkbox" name="remember" id="id_remember_password_modal">
                                <label class="form-check-label remember-text" for="id_remember_password_modal">
                                    Remember me
                                </label>
                            </div>
                        </div>
                        <div class="col-sm-10">
                            <button class="btn btn-primary mt-3 w-100" type="submit">Sign in</button>
                        </div>
                    </div>
                </form>
                <div class="mb-3 row justify-content-around">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-3">
                        <a href="#" class="btn fa fa-google" type="button" style="background: #dd4b39; color: white;"> Sign in with Google</a>
                        <a href="#" class="btn fa fa-facebook" type="button" style="background: #3B5998; color: white;"> Sign in with Facebook</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer" style="border-top: 0 none; background-color:#16161a;">
                <div class="d-grid mx-auto">
                    <p class="m-0" style="color:white">Not a member yet? <a href="{% url 'account_signup' %}" style="text-decoration: none;">Sign Up here</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

Photogram/client/templates/config/default.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Photogram{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body class="bg-dark">
    {% include "config/bootstrap/navbar.html" %}
    {% block body %}
        {% block content %}
            <h1>Default Content</h1>
        {% endblock %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
    <script src="{% static 'js/scripts.css' %}"></script>
</body>
</html>

Photogram/client/templates/gallery/album.html
{% extends "config/default.html" %}

{% block title %}Photogram - {{ photo.title }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row vh-100">
            <div class="d-flex align-items-center justify-content-center col-sm-9 bg-black">
                <img class="img-fluid w-75" src="{{ photo.image.url }}" />
            </div>
            <div class="col-sm-3 px-4">
                <div class="container d-flex align-items-start px-0 pt-5">
                    <a href="{% url 'profiles:detail' photo.author.username %}" >
                        <img src="{{ photo.author.profile.image.url }}" class="rounded-circle" style="float: left; width: 50px; height: auto;" alt="Avatar" />
                    </a>
                    <div class="px-3">
                        <a class="link-light text-decoration-none" href="{% url 'profiles:detail' photo.author.username %}" style="font-size: 20px">{{ photo.author.username }}</a>
                        <h6 style="color: white;">{{ photo.author.profile.headline }}</h6>
                    </div>
                </div>
                <br>
                <div class="text-light">
                    <h5>{{ photo.title }}</h4>
                    <p>{{ photo.description }}</p>
                    <p>photoed on {{ photo.date }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Photogram/client/templates/gallery/home.html
{% extends 'config/default.html' %}

{% block title %}Photogram - Gallery{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row p-0" data-masonry='{"percentPosition": true }'>
            {% for photo in photos %}
            <div class="col-sm-6 col-lg-4 p-0 w-25">
                <a href="{% url 'gallery:album' photo.id %}">
                    <img src="{{ photo.image.url }}" alt="{{ photo.title }}" class="img-fluid" loading="lazy" />
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Photogram/client/templates/gallery/new.html
{% extends "config/default.html" %}

{% block title %}Upload a new photo{% endblock title %}

{% block body %}
<div class="d-flex min-vh-100 justify-content-center align-items-center" style="color: white">
    <div class="card bg-dark" data-bs-theme="dark">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
    </div>
</div>
{% endblock body %}

Photogram/client/templates/profile/detail.html
{% extends 'config/default.html' %}

{% block title %}Photogram - {{ user.username }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row p-0" data-masonry='{"percentPosition": true }'>
            {% for photo in photos %}
            <div class="col-sm-6 col-lg-4 p-0 w-25">
                <a href="{% url 'gallery:album' photo.author.id %}">
                    <img src="{{ photo.author.image.url }}" alt="{{ photo.title }}" class="img-fluid" loading="lazy" />
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}